spring:
  application:
    name: evaluator
  main:
    allow-bean-definition-overriding: true
  data:
    cassandra:
      keyspace-name: evaluator
      contact-points: localhost
      port: 9042
      schema-action: create_if_not_exists
server:
  port: ${PORT:8081}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
